# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '9.7.0'
    postgresql:
      repo: 'puppetlabs/postgresql'
      ref: '10.5.0'
    systemd:
      repo: 'puppet/systemd'
      ref: '9.0.1'
    concat:
      repo: 'puppetlabs/concat'
      ref: '9.1.0'
    yumrepo_core:
      repo: 'puppetlabs/yumrepo_core'
      ref: '2.1.0'
    apt: # dependency of postgresql
      repo: 'puppetlabs/apt'
      ref: '10.0.1'
    inifile: # dependency of systemd
      repo: 'puppetlabs/inifile'
      ref: '6.0.0'
    yum:
      repo: 'puppet/yum'
      ref: '7.3.0'
    augeas:
      repo: 'puppetlabs/augeas_core'
      ref: '1.5.0'
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
